version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: var-naming
          disabled: true

formatters:
  enable:
    - gofmt

