version: 2

builds:
  - main: ./cmd/honeycomb
    binary: honeycomb
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip
