version: 2

builds:
  - main: ./cmd/honeycomb
    binary: honeycomb
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^build\\(deps\\):"
  groups:
    - title: Features
      regexp: "^.*feat(\\(.+\\))??!?:.+$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix(\\(.+\\))??!?:.+$"
      order: 1
    - title: Others
      order: 999
